### ISSUE TITLE
ISSUE: As a driver, I can see the numbers of the students in my shifts

### ISSUE THREAD

**Issue by bzamora020** [ucsb-cs156/proj-gauchoride#47] opened 2023-05-25 00:52 UTC
### Have you updated the title?

- [X] I have updated the issue's title.

### As a...

driver

### I can...

See a list of phone numbers of the riders that will pick up on their shifts

### So that...

They can reach out to the riders in case of any emergency

### Discussion

Note: You might want to complete issue #48 Before completing this one.

In case of any emergency, drivers might need to reach out to the riders that they are supposed to pick up sometime soon. In case the original driver might not be able to pick them up

### Acceptance Criteria

- [ ] (Suggestion) On the drivers' page, the drivers have a table where they can see the numbers of the riders they have for their upcoming shifts

### Implementation Todos

Frontend:
- [ ] Display table with titles: name, cellphone.
- [ ] Table is populated with the data of the riders the driver was assigned to

Backend:
- [ ] There is an endpoint to fetch the riders' data associated with the driver (Get request)

Testing:
- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by pconrad** [comment] 2023-08-12 02:59
closed; duplicate of #48

**Closed by pconrad** 2023-08-12 02:59 UTC
